
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '].\x1fU\xe3\xfb2\x8bt\xf65\x7f\x99\xb4xQ'
    
_lr_action_items = {'RPAREN':([4,11,12,16,18,19,21,22,],[-9,-10,19,21,-8,-12,-11,-7,]),'NAME':([0,2,3,4,6,7,9,10,11,13,15,17,18,19,20,21,22,],[3,11,-10,-9,3,11,-6,11,-10,11,-4,11,-8,-12,-5,-11,-7,]),'INT':([0,2,3,4,6,7,9,10,11,13,15,17,18,19,20,21,22,],[4,4,-10,-9,4,4,-6,4,-10,4,-4,4,-8,-12,-5,-11,-7,]),'EQUALS':([3,],[13,]),'PLUS':([3,4,9,11,12,15,18,19,20,21,22,],[-10,-9,17,-10,17,17,-8,-12,17,-11,-7,]),'LPAREN':([0,2,3,4,6,7,8,9,10,11,13,15,17,18,19,20,21,22,],[2,2,-10,-9,2,2,16,-6,2,-10,2,-4,2,-8,-12,-5,-11,-7,]),'PRINT':([0,3,4,6,9,11,15,18,19,20,21,22,],[7,-10,-9,7,-6,-10,-4,-8,-12,-5,-11,-7,]),'INPUT':([0,2,3,4,6,7,9,10,11,13,15,17,18,19,20,21,22,],[8,8,-10,-9,8,8,-6,8,-10,8,-4,8,-8,-12,-5,-11,-7,]),'MINUS':([0,2,3,4,6,7,9,10,11,13,15,17,18,19,20,21,22,],[10,10,-10,-9,10,10,-6,10,-10,10,-4,10,-8,-12,-5,-11,-7,]),'$end':([0,1,3,4,5,6,9,11,14,15,18,19,20,21,22,],[-2,-1,-10,-9,0,-2,-6,-10,-3,-4,-8,-12,-5,-11,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt_list':([0,6,],[1,14,]),'expression':([0,2,6,7,10,13,17,],[9,12,9,15,18,20,22,]),'statement':([0,6,],[6,6,]),'module':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> stmt_list','module',1,'p_module','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',9),
  ('stmt_list -> <empty>','stmt_list',0,'p_empty_list','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',13),
  ('stmt_list -> statement stmt_list','stmt_list',2,'p_extend_list','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',17),
  ('statement -> PRINT expression','statement',2,'p_print_statement','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',21),
  ('statement -> NAME EQUALS expression','statement',3,'p_assign_expression','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',25),
  ('statement -> expression','statement',1,'p_discard_statement','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',29),
  ('expression -> expression PLUS expression','expression',3,'p_plus_expression','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',33),
  ('expression -> MINUS expression','expression',2,'p_minus_expression','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',37),
  ('expression -> INT','expression',1,'p_int_expression','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',42),
  ('expression -> NAME','expression',1,'p_name','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',46),
  ('expression -> INPUT LPAREN RPAREN','expression',3,'p_input_function','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',50),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_paran_expression','/home/hema/Desktop/compiler/lab2/Hw/P0parser.py',56),
]
